language: php

env:
  global:
    - SYMFONY_VERSION="3.4.*"
    - COMPOSER_FLAGS="--prefer-stable"

matrix:
  include:
    - php: 7.2
    # Build ensuring minimum dependencies are valid
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
    - php: 7.2
      env: SYMFONY_VERSION="4.1.*"
    - php: 7.2
      env: SYMFONY_VERSION="4.2.*"
    - php: 7.2
      env: SYMFONY_VERSION="4.3.*@dev"
    - php: 7.3
      env: SYMFONY_VERSION="4.1.*"
    - php: nightly
  allow_failures:
    # Allow failures on next Symfony minor, should always be tested on newest stable PHP branch
    - php: 7.2
      env: SYMFONY_VERSION="4.3.*@dev"
    - php: nightly

before_script:
  - composer self-update
  - composer require --no-update symfony/symfony:${SYMFONY_VERSION}
  - composer update $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit -c phpunit.xml --coverage-text
