language: php

dist: xenial

addons:
  apt_packages:
    - rabbitmq-server

env:
  global:
    - SYMFONY_REQUIRE="3.4.*"
    - COMPOSER_FLAGS="--prefer-stable"

matrix:
  include:
    - php: 7.2
    # Build ensuring minimum dependencies are valid
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
    - php: 7.3
      env: SYMFONY_REQUIRE="4.4.*"
    - php: 7.4
      env: SYMFONY_REQUIRE="4.4.*"
    - php: 7.4
      env: SYMFONY_REQUIRE="5.0.*"
    - php: 7.4
      env: SYMFONY_REQUIRE="5.1.*@dev"
    - php: nightly
      env: SYMFONY_REQUIRE="4.4.*"
  allow_failures:
    # Allow failures with Symfony 5.0 until Ratchet is updated to support it
    - php: 7.4
      env: SYMFONY_REQUIRE="5.0.*"
    # Allow failures on next Symfony minor, should always be tested on newest stable PHP branch
    - php: 7.4
      env: SYMFONY_REQUIRE="5.1.*@dev"
    - php: nightly
      env: SYMFONY_REQUIRE="4.4.*"

cache:
  directories:
    - $HOME/.composer/cache

services:
  - rabbitmq

before_install:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer self-update
  - sudo apt update
  - sudo apt install -y librabbitmq-dev
  - yes '' | pecl install -f amqp

before_script:
  - composer global require --no-scripts --no-plugins symfony/flex
  - composer require --dev --no-update gos/react-amqp:^0.3
  - composer update $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit
